[project]
authors = ["Christopher Nair <chrisnair1@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "udp_camera_streaming"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
opencv = ">=4.11.0,<5"
python = ">=3.13.3,<3.14"
numpy = ">=2.2.5,<3"
